//! Release registry facts checked against ArgumentTypeInfos in the cached
//! 1.20.1, 1.20.2, 1.20.4, 1.20.6, 1.21.1, 1.21.3, 1.21.4, 1.21.5,
//! 1.21.6, 1.21.8, 1.21.10, 1.21.11, 26.1.2 and 26.2 server jars.
//! Pinned schemas use the incorrect name `minecraft:nbt` for nbt_compound_tag;
//! protocol 776 also renames color to team_color. Development-only test parsers
//! are not in the production release registry. No implementation is reproduced.
use crate::{Error, Result, Version};

/// Stable semantic identity; IDs are release-specific. This is the command
/// argument registry, not an item/block or dynamic data-pack registry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParserKind {
    Bool,
    Float,
    Double,
    Integer,
    Long,
    String,
    Entity,
    GameProfile,
    BlockPos,
    ColumnPos,
    Vec3,
    Vec2,
    BlockState,
    BlockPredicate,
    ItemStack,
    ItemPredicate,
    Color,
    Component,
    Message,
    NbtCompoundTag,
    NbtTag,
    NbtPath,
    Objective,
    ObjectiveCriteria,
    Operation,
    Particle,
    Angle,
    Rotation,
    ScoreboardSlot,
    ScoreHolder,
    Swizzle,
    Team,
    ItemSlot,
    ResourceLocation,
    Function,
    EntityAnchor,
    IntRange,
    FloatRange,
    Dimension,
    Gamemode,
    Time,
    ResourceOrTag,
    ResourceOrTagKey,
    Resource,
    ResourceKey,
    TemplateMirror,
    TemplateRotation,
    Heightmap,
    Uuid,
    Style,
    ItemSlots,
    LootTable,
    LootPredicate,
    LootModifier,
    ResourceSelector,
    HexColor,
    Dialog,
    TeamColor,
}
impl ParserKind {
    pub const fn name(self) -> &'static str {
        match self {
            Self::Bool => "brigadier:bool",
            Self::Float => "brigadier:float",
            Self::Double => "brigadier:double",
            Self::Integer => "brigadier:integer",
            Self::Long => "brigadier:long",
            Self::String => "brigadier:string",
            Self::Entity => "minecraft:entity",
            Self::GameProfile => "minecraft:game_profile",
            Self::BlockPos => "minecraft:block_pos",
            Self::ColumnPos => "minecraft:column_pos",
            Self::Vec3 => "minecraft:vec3",
            Self::Vec2 => "minecraft:vec2",
            Self::BlockState => "minecraft:block_state",
            Self::BlockPredicate => "minecraft:block_predicate",
            Self::ItemStack => "minecraft:item_stack",
            Self::ItemPredicate => "minecraft:item_predicate",
            Self::Color => "minecraft:color",
            Self::Component => "minecraft:component",
            Self::Message => "minecraft:message",
            Self::NbtCompoundTag => "minecraft:nbt_compound_tag",
            Self::NbtTag => "minecraft:nbt_tag",
            Self::NbtPath => "minecraft:nbt_path",
            Self::Objective => "minecraft:objective",
            Self::ObjectiveCriteria => "minecraft:objective_criteria",
            Self::Operation => "minecraft:operation",
            Self::Particle => "minecraft:particle",
            Self::Angle => "minecraft:angle",
            Self::Rotation => "minecraft:rotation",
            Self::ScoreboardSlot => "minecraft:scoreboard_slot",
            Self::ScoreHolder => "minecraft:score_holder",
            Self::Swizzle => "minecraft:swizzle",
            Self::Team => "minecraft:team",
            Self::ItemSlot => "minecraft:item_slot",
            Self::ResourceLocation => "minecraft:resource_location",
            Self::Function => "minecraft:function",
            Self::EntityAnchor => "minecraft:entity_anchor",
            Self::IntRange => "minecraft:int_range",
            Self::FloatRange => "minecraft:float_range",
            Self::Dimension => "minecraft:dimension",
            Self::Gamemode => "minecraft:gamemode",
            Self::Time => "minecraft:time",
            Self::ResourceOrTag => "minecraft:resource_or_tag",
            Self::ResourceOrTagKey => "minecraft:resource_or_tag_key",
            Self::Resource => "minecraft:resource",
            Self::ResourceKey => "minecraft:resource_key",
            Self::TemplateMirror => "minecraft:template_mirror",
            Self::TemplateRotation => "minecraft:template_rotation",
            Self::Heightmap => "minecraft:heightmap",
            Self::Uuid => "minecraft:uuid",
            Self::Style => "minecraft:style",
            Self::ItemSlots => "minecraft:item_slots",
            Self::LootTable => "minecraft:loot_table",
            Self::LootPredicate => "minecraft:loot_predicate",
            Self::LootModifier => "minecraft:loot_modifier",
            Self::ResourceSelector => "minecraft:resource_selector",
            Self::HexColor => "minecraft:hex_color",
            Self::Dialog => "minecraft:dialog",
            Self::TeamColor => "minecraft:team_color",
        }
    }
    pub fn id(self, version: Version) -> Result<i32> {
        parser_registry(version)
            .iter()
            .position(|kind| *kind == self)
            .map(|id| id as i32)
            .ok_or(Error::Unsupported("command parser in selected release"))
    }
    pub fn from_id(id: i32, version: Version) -> Result<Self> {
        usize::try_from(id)
            .ok()
            .and_then(|id| parser_registry(version).get(id))
            .copied()
            .ok_or(Error::Unsupported("unknown command parser ID"))
    }
}
/// All production parser kinds, in exact wire ID order.
pub fn parser_registry(version: Version) -> &'static [ParserKind] {
    match version.protocol() {
        763..=764 => P763,
        765 => P765,
        766..=769 => P766,
        770 => P770,
        771..=775 => P771,
        776 => P776,
        _ => unreachable!(),
    }
}

const P763: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::Color,
    ParserKind::Component,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::Uuid,
];

const P765: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::Color,
    ParserKind::Component,
    ParserKind::Style,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::Uuid,
];

const P766: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::Color,
    ParserKind::Component,
    ParserKind::Style,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ItemSlots,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::LootTable,
    ParserKind::LootPredicate,
    ParserKind::LootModifier,
    ParserKind::Uuid,
];

const P770: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::Color,
    ParserKind::Component,
    ParserKind::Style,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ItemSlots,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::ResourceSelector,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::LootTable,
    ParserKind::LootPredicate,
    ParserKind::LootModifier,
    ParserKind::Uuid,
];

const P771: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::Color,
    ParserKind::HexColor,
    ParserKind::Component,
    ParserKind::Style,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ItemSlots,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::ResourceSelector,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::LootTable,
    ParserKind::LootPredicate,
    ParserKind::LootModifier,
    ParserKind::Dialog,
    ParserKind::Uuid,
];

const P776: &[ParserKind] = &[
    ParserKind::Bool,
    ParserKind::Float,
    ParserKind::Double,
    ParserKind::Integer,
    ParserKind::Long,
    ParserKind::String,
    ParserKind::Entity,
    ParserKind::GameProfile,
    ParserKind::BlockPos,
    ParserKind::ColumnPos,
    ParserKind::Vec3,
    ParserKind::Vec2,
    ParserKind::BlockState,
    ParserKind::BlockPredicate,
    ParserKind::ItemStack,
    ParserKind::ItemPredicate,
    ParserKind::TeamColor,
    ParserKind::HexColor,
    ParserKind::Component,
    ParserKind::Style,
    ParserKind::Message,
    ParserKind::NbtCompoundTag,
    ParserKind::NbtTag,
    ParserKind::NbtPath,
    ParserKind::Objective,
    ParserKind::ObjectiveCriteria,
    ParserKind::Operation,
    ParserKind::Particle,
    ParserKind::Angle,
    ParserKind::Rotation,
    ParserKind::ScoreboardSlot,
    ParserKind::ScoreHolder,
    ParserKind::Swizzle,
    ParserKind::Team,
    ParserKind::ItemSlot,
    ParserKind::ItemSlots,
    ParserKind::ResourceLocation,
    ParserKind::Function,
    ParserKind::EntityAnchor,
    ParserKind::IntRange,
    ParserKind::FloatRange,
    ParserKind::Dimension,
    ParserKind::Gamemode,
    ParserKind::Time,
    ParserKind::ResourceOrTag,
    ParserKind::ResourceOrTagKey,
    ParserKind::Resource,
    ParserKind::ResourceKey,
    ParserKind::ResourceSelector,
    ParserKind::TemplateMirror,
    ParserKind::TemplateRotation,
    ParserKind::Heightmap,
    ParserKind::LootTable,
    ParserKind::LootPredicate,
    ParserKind::LootModifier,
    ParserKind::Dialog,
    ParserKind::Uuid,
];
