//! Semantic particle options and release-specific registry IDs.
//!
//! Unknown IDs are Unsupported: particles have no length prefix and cannot be
//! skipped safely. Item particles share the inventory component coverage limits.
//! Wire corrections checked against the release server codecs: legacy vibration
//! entity eye height is f32; RGB transition scale moves last in 766; packed dust
//! starts in 768 and remains packed in 776; trail duration starts in 769 and is
//! still present in 776; item templates replace stacks in 775.
use crate::{
    codec::{BlockPosition, Reader, Writer},
    packet::inventory::{self, Budget, ItemData, ItemStack, Slot},
    Error, Limits, Result, Version,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParticleWire {
    Unit,
    BlockState,
    DustRgb,
    DustPacked,
    TransitionLegacy,
    TransitionRgb,
    TransitionPacked,
    Color,
    Item,
    ItemTemplate,
    VibrationLegacy,
    Vibration,
    SculkCharge,
    Shriek,
    TrailWithoutDuration,
    Trail,
    Power,
    Spell,
    Geyser,
    GeyserBase,
}
// BEGIN GENERATED PARTICLE REGISTRIES
/// Index is the release-specific particle registry ID.
pub fn particle_registry(version: Version) -> &'static [(&'static str, ParticleWire)] {
    match version.protocol() {
        763 | 764 => PARTICLES_0,
        765 => PARTICLES_1,
        766 | 767 => PARTICLES_2,
        768 => PARTICLES_3,
        769 => PARTICLES_4,
        770..=772 => PARTICLES_5,
        773 | 774 => PARTICLES_6,
        775 => PARTICLES_7,
        776 => PARTICLES_8,
        _ => unreachable!(),
    }
}
const PARTICLES_0: &[(&str, ParticleWire)] = &[
    ("ambient_entity_effect", ParticleWire::Unit),
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustRgb),
    ("dust_color_transition", ParticleWire::TransitionLegacy),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Unit),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::VibrationLegacy),
    ("item_slime", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
];
const PARTICLES_1: &[(&str, ParticleWire)] = &[
    ("ambient_entity_effect", ParticleWire::Unit),
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustRgb),
    ("dust_color_transition", ParticleWire::TransitionLegacy),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Unit),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("gust_emitter", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::VibrationLegacy),
    ("item_slime", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("gust_dust", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
];
const PARTICLES_2: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustRgb),
    ("dust_color_transition", ParticleWire::TransitionRgb),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::Vibration),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
];
const PARTICLES_3: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::TrailWithoutDuration),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
];
const PARTICLES_4: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("pale_oak_leaves", ParticleWire::Unit),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::Trail),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
];
const PARTICLES_5: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Unit),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Unit),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("pale_oak_leaves", ParticleWire::Unit),
    ("tinted_leaves", ParticleWire::Color),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Unit),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Unit),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::Trail),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
    ("firefly", ParticleWire::Unit),
];
const PARTICLES_6: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("copper_fire_flame", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Power),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Spell),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("pale_oak_leaves", ParticleWire::Unit),
    ("tinted_leaves", ParticleWire::Color),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Color),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Spell),
    ("item", ParticleWire::Item),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::Trail),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
    ("firefly", ParticleWire::Unit),
];
const PARTICLES_7: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("cloud", ParticleWire::Unit),
    ("copper_fire_flame", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Power),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Spell),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("pale_oak_leaves", ParticleWire::Unit),
    ("tinted_leaves", ParticleWire::Color),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Color),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Spell),
    ("item", ParticleWire::ItemTemplate),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::Trail),
    ("pause_mob_growth", ParticleWire::Unit),
    ("reset_mob_growth", ParticleWire::Unit),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
    ("firefly", ParticleWire::Unit),
];
const PARTICLES_8: &[(&str, ParticleWire)] = &[
    ("angry_villager", ParticleWire::Unit),
    ("block", ParticleWire::BlockState),
    ("block_marker", ParticleWire::BlockState),
    ("bubble", ParticleWire::Unit),
    ("sulfur_bubbles", ParticleWire::Unit),
    ("noxious_gas", ParticleWire::Unit),
    ("noxious_gas_cloud", ParticleWire::Unit),
    ("geyser", ParticleWire::Geyser),
    ("geyser_base", ParticleWire::GeyserBase),
    ("geyser_poof", ParticleWire::GeyserBase),
    ("geyser_plume", ParticleWire::Geyser),
    ("cloud", ParticleWire::Unit),
    ("copper_fire_flame", ParticleWire::Unit),
    ("crit", ParticleWire::Unit),
    ("damage_indicator", ParticleWire::Unit),
    ("dragon_breath", ParticleWire::Power),
    ("dripping_lava", ParticleWire::Unit),
    ("falling_lava", ParticleWire::Unit),
    ("landing_lava", ParticleWire::Unit),
    ("dripping_water", ParticleWire::Unit),
    ("falling_water", ParticleWire::Unit),
    ("dust", ParticleWire::DustPacked),
    ("dust_color_transition", ParticleWire::TransitionPacked),
    ("effect", ParticleWire::Spell),
    ("elder_guardian", ParticleWire::Unit),
    ("enchanted_hit", ParticleWire::Unit),
    ("enchant", ParticleWire::Unit),
    ("end_rod", ParticleWire::Unit),
    ("entity_effect", ParticleWire::Color),
    ("explosion_emitter", ParticleWire::Unit),
    ("explosion", ParticleWire::Unit),
    ("gust", ParticleWire::Unit),
    ("small_gust", ParticleWire::Unit),
    ("gust_emitter_large", ParticleWire::Unit),
    ("gust_emitter_small", ParticleWire::Unit),
    ("sonic_boom", ParticleWire::Unit),
    ("falling_dust", ParticleWire::BlockState),
    ("firework", ParticleWire::Unit),
    ("fishing", ParticleWire::Unit),
    ("flame", ParticleWire::Unit),
    ("infested", ParticleWire::Unit),
    ("cherry_leaves", ParticleWire::Unit),
    ("pale_oak_leaves", ParticleWire::Unit),
    ("tinted_leaves", ParticleWire::Color),
    ("sculk_soul", ParticleWire::Unit),
    ("sculk_charge", ParticleWire::SculkCharge),
    ("sculk_charge_pop", ParticleWire::Unit),
    ("soul_fire_flame", ParticleWire::Unit),
    ("soul", ParticleWire::Unit),
    ("flash", ParticleWire::Color),
    ("happy_villager", ParticleWire::Unit),
    ("composter", ParticleWire::Unit),
    ("heart", ParticleWire::Unit),
    ("instant_effect", ParticleWire::Spell),
    ("item", ParticleWire::ItemTemplate),
    ("vibration", ParticleWire::Vibration),
    ("trail", ParticleWire::Trail),
    ("pause_mob_growth", ParticleWire::Unit),
    ("reset_mob_growth", ParticleWire::Unit),
    ("item_slime", ParticleWire::Unit),
    ("item_cobweb", ParticleWire::Unit),
    ("item_snowball", ParticleWire::Unit),
    ("large_smoke", ParticleWire::Unit),
    ("lava", ParticleWire::Unit),
    ("mycelium", ParticleWire::Unit),
    ("note", ParticleWire::Unit),
    ("poof", ParticleWire::Unit),
    ("portal", ParticleWire::Unit),
    ("rain", ParticleWire::Unit),
    ("smoke", ParticleWire::Unit),
    ("white_smoke", ParticleWire::Unit),
    ("sneeze", ParticleWire::Unit),
    ("spit", ParticleWire::Unit),
    ("squid_ink", ParticleWire::Unit),
    ("sweep_attack", ParticleWire::Unit),
    ("totem_of_undying", ParticleWire::Unit),
    ("underwater", ParticleWire::Unit),
    ("splash", ParticleWire::Unit),
    ("witch", ParticleWire::Unit),
    ("bubble_pop", ParticleWire::Unit),
    ("current_down", ParticleWire::Unit),
    ("bubble_column_up", ParticleWire::Unit),
    ("nautilus", ParticleWire::Unit),
    ("dolphin", ParticleWire::Unit),
    ("campfire_cosy_smoke", ParticleWire::Unit),
    ("campfire_signal_smoke", ParticleWire::Unit),
    ("dripping_honey", ParticleWire::Unit),
    ("falling_honey", ParticleWire::Unit),
    ("landing_honey", ParticleWire::Unit),
    ("falling_nectar", ParticleWire::Unit),
    ("falling_spore_blossom", ParticleWire::Unit),
    ("ash", ParticleWire::Unit),
    ("crimson_spore", ParticleWire::Unit),
    ("warped_spore", ParticleWire::Unit),
    ("spore_blossom_air", ParticleWire::Unit),
    ("dripping_obsidian_tear", ParticleWire::Unit),
    ("falling_obsidian_tear", ParticleWire::Unit),
    ("landing_obsidian_tear", ParticleWire::Unit),
    ("reverse_portal", ParticleWire::Unit),
    ("white_ash", ParticleWire::Unit),
    ("small_flame", ParticleWire::Unit),
    ("snowflake", ParticleWire::Unit),
    ("dripping_dripstone_lava", ParticleWire::Unit),
    ("falling_dripstone_lava", ParticleWire::Unit),
    ("dripping_dripstone_water", ParticleWire::Unit),
    ("falling_dripstone_water", ParticleWire::Unit),
    ("glow_squid_ink", ParticleWire::Unit),
    ("glow", ParticleWire::Unit),
    ("wax_on", ParticleWire::Unit),
    ("wax_off", ParticleWire::Unit),
    ("electric_spark", ParticleWire::Unit),
    ("scrape", ParticleWire::Unit),
    ("shriek", ParticleWire::Shriek),
    ("egg_crack", ParticleWire::Unit),
    ("dust_plume", ParticleWire::Unit),
    ("trial_spawner_detection", ParticleWire::Unit),
    ("trial_spawner_detection_ominous", ParticleWire::Unit),
    ("vault_connection", ParticleWire::Unit),
    ("dust_pillar", ParticleWire::BlockState),
    ("ominous_spawning", ParticleWire::Unit),
    ("raid_omen", ParticleWire::Unit),
    ("trial_omen", ParticleWire::Unit),
    ("block_crumble", ParticleWire::BlockState),
    ("firefly", ParticleWire::Unit),
    ("sulfur_cube_goo", ParticleWire::Unit),
];
// END GENERATED PARTICLE REGISTRIES

#[derive(Debug, Clone, PartialEq)]
pub struct Particle {
    /// Registry name without the minecraft namespace; use particle_registry for this release.
    pub kind: &'static str,
    pub data: ParticleData,
}
#[derive(Debug, Clone, PartialEq)]
pub enum VibrationDestination {
    Block(BlockPosition),
    Entity { entity_id: i32, eye_height: f32 },
}
#[derive(Debug, Clone, PartialEq)]
pub enum ParticleData {
    Unit,
    BlockState(i32),
    DustRgb {
        color: [f32; 3],
        scale: f32,
    },
    DustPacked {
        color: i32,
        scale: f32,
    },
    TransitionRgb {
        from: [f32; 3],
        to: [f32; 3],
        scale: f32,
    },
    TransitionPacked {
        from: i32,
        to: i32,
        scale: f32,
    },
    /// Raw packed color bits, including alpha where defined by the particle.
    Color(i32),
    Item(Box<Slot>),
    /// 26.1+ uses item ID, count, then component patch; no empty sentinel.
    ItemTemplate(Box<ItemStack>),
    Vibration {
        destination: VibrationDestination,
        ticks: i32,
    },
    SculkCharge {
        roll: f32,
    },
    Shriek {
        delay: i32,
    },
    /// Duration is absent only in protocol 768 (1.21.2/1.21.3).
    Trail {
        target: [f64; 3],
        color: i32,
        duration: Option<i32>,
    },
    Power(f32),
    Spell {
        color: i32,
        power: f32,
    },
    Geyser {
        water_blocks: i32,
    },
    GeyserBase {
        water_blocks: i32,
        burst_impulse_base: f32,
    },
}
fn nonnegative(n: i32) -> Result<i32> {
    if n < 0 {
        Err(Error::Invalid("negative particle integer"))
    } else {
        Ok(n)
    }
}
fn finite(n: f32) -> Result<f32> {
    if n.is_finite() {
        Ok(n)
    } else {
        Err(Error::Invalid("non-finite particle float"))
    }
}
fn finite64(n: f64) -> Result<f64> {
    if n.is_finite() {
        Ok(n)
    } else {
        Err(Error::Invalid("non-finite particle coordinate"))
    }
}
fn rgb(r: &mut Reader<'_>) -> Result<[f32; 3]> {
    Ok([finite(r.f32()?)?, finite(r.f32()?)?, finite(r.f32()?)?])
}
fn write_rgb(w: &mut Writer, value: &[f32; 3]) -> Result<()> {
    for n in value {
        w.f32(finite(*n)?);
    }
    Ok(())
}
pub fn particle_id(version: Version, name: &str) -> Result<i32> {
    particle_registry(version)
        .iter()
        .position(|(n, _)| *n == name)
        .map(|id| id as i32)
        .ok_or(Error::Unsupported("particle in selected release"))
}
pub(super) fn read(r: &mut Reader<'_>, version: Version, b: &mut Budget) -> Result<Particle> {
    b.charge(1)?;
    let id = nonnegative(r.var_i32()?)? as usize;
    let (kind, wire) = particle_registry(version)
        .get(id)
        .copied()
        .ok_or(Error::Unsupported("unknown particle registry ID"))?;
    use ParticleData as D;
    use ParticleWire as W;
    let data = match wire {
        W::Unit => D::Unit,
        W::BlockState => D::BlockState(nonnegative(r.var_i32()?)?),
        W::DustRgb => D::DustRgb {
            color: rgb(r)?,
            scale: finite(r.f32()?)?,
        },
        W::DustPacked => D::DustPacked {
            color: r.i32()?,
            scale: finite(r.f32()?)?,
        },
        W::TransitionLegacy => {
            let from = rgb(r)?;
            let scale = finite(r.f32()?)?;
            D::TransitionRgb {
                from,
                scale,
                to: rgb(r)?,
            }
        }
        W::TransitionRgb => D::TransitionRgb {
            from: rgb(r)?,
            to: rgb(r)?,
            scale: finite(r.f32()?)?,
        },
        W::TransitionPacked => D::TransitionPacked {
            from: r.i32()?,
            to: r.i32()?,
            scale: finite(r.f32()?)?,
        },
        W::Color => D::Color(r.i32()?),
        W::Item => {
            let slot = inventory::read_slot(r, version, b, 0)?;
            if version.protocol() >= 766 && matches!(slot, Slot::Empty) {
                return Err(Error::Invalid("empty item particle"));
            }
            D::Item(Box::new(slot))
        }
        W::ItemTemplate => {
            b.charge(1)?;
            let item_id = nonnegative(r.var_i32()?)?;
            let count = nonnegative(r.var_i32()?)?;
            D::ItemTemplate(Box::new(ItemStack {
                item_id,
                count,
                data: ItemData::Components(inventory::read_patch(r, version, b, 0)?),
            }))
        }
        W::VibrationLegacy | W::Vibration => {
            let source = if wire == W::VibrationLegacy {
                match r.string(32767)? {
                    "minecraft:block" | "block" => 0,
                    "minecraft:entity" | "entity" => 1,
                    _ => return Err(Error::Unsupported("vibration position source")),
                }
            } else {
                nonnegative(r.var_i32()?)?
            };
            let destination = match source {
                0 => VibrationDestination::Block(BlockPosition::unpack(r.i64()?)),
                1 => VibrationDestination::Entity {
                    entity_id: nonnegative(r.var_i32()?)?,
                    eye_height: finite(r.f32()?)?,
                },
                _ => return Err(Error::Unsupported("vibration position source")),
            };
            D::Vibration {
                destination,
                ticks: nonnegative(r.var_i32()?)?,
            }
        }
        W::SculkCharge => D::SculkCharge {
            roll: finite(r.f32()?)?,
        },
        W::Shriek => D::Shriek {
            delay: nonnegative(r.var_i32()?)?,
        },
        W::Trail | W::TrailWithoutDuration => D::Trail {
            target: [
                finite64(r.f64()?)?,
                finite64(r.f64()?)?,
                finite64(r.f64()?)?,
            ],
            color: r.i32()?,
            duration: if wire == W::Trail {
                Some(nonnegative(r.var_i32()?)?)
            } else {
                None
            },
        },
        W::Power => D::Power(finite(r.f32()?)?),
        W::Spell => D::Spell {
            color: r.i32()?,
            power: finite(r.f32()?)?,
        },
        W::Geyser => D::Geyser {
            water_blocks: r.i32()?,
        },
        W::GeyserBase => D::GeyserBase {
            water_blocks: r.i32()?,
            burst_impulse_base: finite(r.f32()?)?,
        },
    };
    Ok(Particle { kind, data })
}
pub(super) fn write(
    particle: &Particle,
    w: &mut Writer,
    version: Version,
    b: &mut Budget,
) -> Result<()> {
    b.charge(1)?;
    let id = particle_id(version, particle.kind)?;
    let wire = particle_registry(version)[id as usize].1;
    w.var_i32(id);
    use ParticleData as D;
    use ParticleWire as W;
    match (wire, &particle.data) {
        (W::Unit, D::Unit) => (),
        (W::BlockState, D::BlockState(n)) => w.var_i32(nonnegative(*n)?),
        (W::DustRgb, D::DustRgb { color, scale }) => {
            write_rgb(w, color)?;
            w.f32(finite(*scale)?);
        }
        (W::DustPacked, D::DustPacked { color, scale }) => {
            w.i32(*color);
            w.f32(finite(*scale)?);
        }
        (W::TransitionLegacy | W::TransitionRgb, D::TransitionRgb { from, to, scale }) => {
            write_rgb(w, from)?;
            if wire == W::TransitionLegacy {
                w.f32(finite(*scale)?);
            }
            write_rgb(w, to)?;
            if wire == W::TransitionRgb {
                w.f32(finite(*scale)?);
            }
        }
        (W::TransitionPacked, D::TransitionPacked { from, to, scale }) => {
            w.i32(*from);
            w.i32(*to);
            w.f32(finite(*scale)?);
        }
        (W::Color, D::Color(color)) => w.i32(*color),
        (W::Item, D::Item(slot)) => {
            if version.protocol() >= 766 && matches!(slot.as_ref(), Slot::Empty) {
                return Err(Error::Invalid("empty item particle"));
            }
            inventory::write_slot(slot, w, version, b, 0)?;
        }
        (W::ItemTemplate, D::ItemTemplate(item)) => {
            b.charge(1)?;
            w.var_i32(nonnegative(item.item_id)?);
            w.var_i32(nonnegative(item.count)?);
            let ItemData::Components(patch) = &item.data else {
                return Err(Error::Invalid("item template requires components"));
            };
            inventory::write_patch(patch, w, version, b, 0)?;
        }
        (W::VibrationLegacy | W::Vibration, D::Vibration { destination, ticks }) => {
            let block = matches!(destination, VibrationDestination::Block(_));
            if wire == W::VibrationLegacy {
                w.string(
                    if block {
                        "minecraft:block"
                    } else {
                        "minecraft:entity"
                    },
                    b.limits.max_string_chars.min(32767),
                )?;
            } else {
                w.var_i32(if block { 0 } else { 1 });
            }
            match destination {
                VibrationDestination::Block(p) => w.i64(p.pack()?),
                VibrationDestination::Entity {
                    entity_id,
                    eye_height,
                } => {
                    w.var_i32(nonnegative(*entity_id)?);
                    w.f32(finite(*eye_height)?);
                }
            }
            w.var_i32(nonnegative(*ticks)?);
        }
        (W::SculkCharge, D::SculkCharge { roll }) => w.f32(finite(*roll)?),
        (W::Shriek, D::Shriek { delay }) => w.var_i32(nonnegative(*delay)?),
        (
            W::Trail | W::TrailWithoutDuration,
            D::Trail {
                target,
                color,
                duration,
            },
        ) => {
            if duration.is_some() != (wire == W::Trail) {
                return Err(Error::Invalid("particle trail duration release"));
            }
            for n in target {
                w.f64(finite64(*n)?);
            }
            w.i32(*color);
            if let Some(duration) = duration {
                w.var_i32(nonnegative(*duration)?);
            }
        }
        (W::Power, D::Power(power)) => w.f32(finite(*power)?),
        (W::Spell, D::Spell { color, power }) => {
            w.i32(*color);
            w.f32(finite(*power)?);
        }
        (W::Geyser, D::Geyser { water_blocks }) => w.i32(*water_blocks),
        (
            W::GeyserBase,
            D::GeyserBase {
                water_blocks,
                burst_impulse_base,
            },
        ) => {
            w.i32(*water_blocks);
            w.f32(finite(*burst_impulse_base)?);
        }
        _ => {
            return Err(Error::Invalid(
                "particle data does not match type or release",
            ))
        }
    }
    b.check_bytes(w)
}
impl Particle {
    pub fn decode(bytes: &[u8], version: Version, limits: Limits) -> Result<Self> {
        if bytes.len() > limits.max_packet {
            return Err(Error::Limit("particle bytes"));
        }
        let mut r = Reader::new(bytes, limits);
        let result = read(&mut r, version, &mut Budget::new(limits))?;
        r.finish()?;
        Ok(result)
    }
    pub fn encode(&self, version: Version, limits: Limits) -> Result<Vec<u8>> {
        let mut w = Writer::new();
        write(self, &mut w, version, &mut Budget::new(limits))?;
        Ok(w.into_inner())
    }
}
