#!/usr/bin/env python3
"""Generate release-specific item component IDs and supported payload layouts.

Run: python3 tools/generate_item_components.py [--check]
Requires Python 3 and rustfmt on PATH; performs no network requests. It verifies
all inputs against research/schema-hashes.json before writing anything. Cargo
uses the checked-in generated module and does not run this script.

The allowlist below is the coverage boundary of inventory.rs. A component that
is not explicitly recognized is emitted as Unsupported; it is never treated as
zero bytes or an opaque length-prefixed payload. Template item stacks (775+) are
intentionally different from Slot and remain unsupported here.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/packet/item_components.rs"
PRIMITIVES = {
    "void": "Unit",
    "varint": "VarInt",
    "i32": "Int",
    "f32": "Float",
    "bool": "Bool",
    "string": "String",
    "anonymousNbt": "Nbt",
    "Slot": "Item",
    "DyeColor": "Enum(15)",
}


def classify(name, shape, protocol):
    if isinstance(shape, str):
        return PRIMITIVES.get(shape, "Unsupported")
    kind, body = shape
    if kind == "mapper" and body["type"] == "varint":
        values = sorted(map(int, body["mappings"]))
        assert values == list(range(len(values))), "non-contiguous enum"
        return f"Enum({values[-1]})"
    if name == "lore":
        assert kind == "array" and body["countType"] == "varint"
        assert body["type"] in ("anonOptionalNbt", "anonymousNbt")
        return "LoreOptional" if body["type"] == "anonOptionalNbt" else "Lore"
    if name in ("enchantments", "stored_enchantments"):
        assert kind == "container" and len(body) in (1, 2)
        return "EnchantmentsTooltip" if len(body) == 2 else "Enchantments"
    if name == "dyed_color":
        return "DyedColorTooltip"
    if name == "custom_model_data":
        return "CustomModelData"
    if name == "tooltip_display":
        return "TooltipDisplay"
    if name == "block_state":
        return "BlockState"
    if name in ("charged_projectiles", "bundle_contents", "container"):
        array = body[0]["type"]
        if kind == "container" and array[0] == "array" and array[1]["type"] == "Slot":
            return "Items"
        return "Unsupported"
    if name == "pot_decorations":
        return "IntList"
    if name in ("entity_data", "block_entity_data") and protocol >= 773:
        return "TypedNbt"
    return "Unsupported"


def generate():
    manifest = json.loads((ROOT / "research/schema-hashes.json").read_text())
    source = json.loads((ROOT / "research/upstream-commit.json").read_text())
    newest_source = json.loads((ROOT / "research/26.2-commit.json").read_text())
    inputs = []
    for entry in sorted(manifest, key=lambda entry: entry["protocol"]):
        if entry["protocol"] < 766:
            continue
        raw = (ROOT / "research/protocols" / f'{entry["schema"]}.json').read_bytes()
        actual = hashlib.sha256(raw).hexdigest()
        if actual != entry["sha256"]:
            raise SystemExit(f"Schema hash mismatch for protocol {entry['protocol']}")
        inputs.append((entry, json.loads(raw)["types"]))
    assert [entry["protocol"] for entry, _ in inputs] == list(range(766, 777))
    out = [
        "// Generated by tools/generate_item_components.py; do not hand edit.",
        f'// Source 766-775: {source["html_url"]}',
        f'// Source 776: {newest_source["html_url"]}',
        "// Unsupported is a fail-closed codec boundary, never an opaque skip.",
    ]
    for entry, _ in inputs:
        out.append(f'// {entry["protocol"]} {entry["schema"]}.json SHA-256 {entry["sha256"]}')
    out += [
        "use super::ComponentWire;",
        "pub(super) fn registry(protocol: i32) -> &'static [(&'static str, ComponentWire)] {",
        "    match protocol {",
    ]
    tables = {}
    for entry, types in inputs:
        protocol = entry["protocol"]
        mapping = types["SlotComponentType"][1]["mappings"]
        fields = types["SlotComponent"][1][1]["type"][1]["fields"]
        assert sorted(map(int, mapping)) == list(range(len(mapping)))
        rows = tuple(
            (mapping[str(i)], classify(mapping[str(i)], fields[mapping[str(i)]], protocol))
            for i in range(len(mapping))
        )
        table = tables.setdefault(rows, f"P{protocol}")
        out.append(f"        {protocol} => {table},")
        unsupported = [name for name, wire in rows if wire == "Unsupported"]
        print(f"{protocol}: {len(rows)-len(unsupported)}/{len(rows)} supported; "
              f"unsupported: {', '.join(unsupported)}")
    out += ["        _ => &[],", "    }", "}"]
    for rows, table in tables.items():
        out.append(f"const {table}: &[(&str, ComponentWire)] = &[")
        for name, wire in rows:
            out.append(f'    ("{name}", ComponentWire::{wire}),')
        out.append("];")
    rustfmt = shutil.which("rustfmt")
    if not rustfmt:
        raise SystemExit("Install rustfmt or add the Rust toolchain to PATH")
    return subprocess.run(
        [rustfmt, "--edition", "2021", "--emit", "stdout"],
        input="\n".join(out) + "\n", text=True, capture_output=True, check=True,
    ).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify checked-in output without writing")
    args = parser.parse_args()
    output = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            raise SystemExit("Item component registry is stale; run without --check")
        print("Checked-in component registry is current")
    else:
        OUTPUT.write_text(output)
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
