#!/usr/bin/env python3
"""Rebuild checked-in packet IDs from protocol JSON fixtures (no build-time codegen)."""
import json,pathlib,hashlib,subprocess,shutil
ROOT=pathlib.Path(__file__).resolve().parents[1]
# Every wire-protocol family, never a guessed nearest-version fallback.
FAMILIES={763:('1.20',['1.20','1.20.1']),764:('1.20.2',['1.20.2']),765:('1.20.3',['1.20.3','1.20.4']),766:('1.20.5',['1.20.5','1.20.6']),767:('1.21.1',['1.21','1.21.1']),768:('1.21.3',['1.21.2','1.21.3']),769:('1.21.4',['1.21.4']),770:('1.21.5',['1.21.5']),771:('1.21.6',['1.21.6']),772:('1.21.8',['1.21.7','1.21.8']),773:('1.21.9',['1.21.9','1.21.10']),774:('1.21.11',['1.21.11']),775:('26.1',['26.1','26.1.1','26.1.2']),776:('26.2',['26.2'])}
dest=ROOT/'src/catalog';dest.mkdir(exist_ok=True)
modules=['// Generated by tools/generate_catalog.py. See PROVENANCE.md.\nuse super::{PacketInfo, State, Direction};\n']
paths=[]
provenance=[]
for protocol,(version,aliases) in FAMILIES.items():
 path=ROOT/'research/protocols'/f'{version}.json';raw=path.read_bytes();d=json.loads(raw)
 out=['// Generated by tools/generate_catalog.py. See PROVENANCE.md.\nuse super::{PacketInfo, State, Direction};\n']
 out.append(f'pub(crate) static P{protocol}: &[PacketInfo] = &[\n')
 modules.append(f'mod p{protocol};\npub(super) use p{protocol}::P{protocol};\n')
 for state,rsstate in [('handshaking','Handshake'),('status','Status'),('login','Login'),('configuration','Configuration'),('play','Play')]:
  for direction,rsdir in [('toClient','Clientbound'),('toServer','Serverbound')]:
   state_data=d.get(state,{}).get(direction,{}).get('types',{}).get('packet')
   if not state_data:continue
   mapping=state_data[1][0]['type'][1]['mappings']
   for wireid,name in mapping.items():out.append(f'    PacketInfo {{state:State::{rsstate}, direction:Direction::{rsdir}, id:{int(wireid,0)}, name:"{name}"}},\n')
 out.append('];\n')
 path=dest/f'p{protocol}.rs';path.write_text(''.join(out));paths.append(path)
 provenance.append({'protocol':protocol,'releases':aliases,'schema':version,'sha256':hashlib.sha256(raw).hexdigest()})
path=dest/'mod.rs';path.write_text(''.join(modules));paths.append(path)
(ROOT/'research/schema-hashes.json').write_text(json.dumps(provenance,indent=2)+'\n')
if not shutil.which('rustfmt'):raise SystemExit('Install rustfmt to format generated modules')
subprocess.run(['rustfmt','--edition','2021',*[str(p) for p in paths]],check=True)
print('Generated',len(paths),'Rust catalog modules')
