#!/usr/bin/env python3
"""Generate checked-in per-protocol catalogs and constant-time group indexes.

No code generation or network access is needed during Cargo builds.
Input schemas are downloaded and hash-checked by fetch_schemas.py.
"""
import hashlib
import json
import pathlib
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
FAMILIES = {
    763: ('1.20', ['1.20', '1.20.1']),
    764: ('1.20.2', ['1.20.2']),
    765: ('1.20.3', ['1.20.3', '1.20.4']),
    766: ('1.20.5', ['1.20.5', '1.20.6']),
    767: ('1.21.1', ['1.21', '1.21.1']),
    768: ('1.21.3', ['1.21.2', '1.21.3']),
    769: ('1.21.4', ['1.21.4']),
    770: ('1.21.5', ['1.21.5']),
    771: ('1.21.6', ['1.21.6']),
    772: ('1.21.8', ['1.21.7', '1.21.8']),
    773: ('1.21.9', ['1.21.9', '1.21.10']),
    774: ('1.21.11', ['1.21.11']),
    775: ('26.1', ['26.1', '26.1.1', '26.1.2']),
    776: ('26.2', ['26.2']),
}
STATES = [('handshaking', 'Handshake'), ('status', 'Status'), ('login', 'Login'),
          ('configuration', 'Configuration'), ('play', 'Play')]
DIRECTIONS = [('toClient', 'Clientbound'), ('toServer', 'Serverbound')]

def corrected_mapping(protocol, state, direction, mapping):
    """Preserve pinned source bytes; apply independently verified wire corrections."""
    mapping = {int(wire_id, 0): name for wire_id, name in mapping.items()}
    if (protocol, state, direction) == (776, 'play', 'toServer'):
        # Official 26.2 client + Paper GameProtocols both register 69 packets.
        # The pinned schema misorders spectator_action and omits UUID spectate.
        expected = {
            0x3e: 'arm_animation', 0x3f: 'spectator_action',
            0x40: 'test_instance_block_action', 0x41: 'block_place',
            0x42: 'use_item', 0x43: 'custom_click_action',
        }
        if {i: n for i, n in mapping.items() if i >= 0x3e} != expected:
            raise SystemExit('Review the protocol-776 spectator/action correction for new schema inputs')
        mapping = {i: n for i, n in mapping.items() if i < 0x3e}
        mapping.update({
            0x3e: 'spectator_action', 0x3f: 'arm_animation', 0x40: 'spectate',
            0x41: 'test_instance_block_action', 0x42: 'block_place',
            0x43: 'use_item', 0x44: 'custom_click_action',
        })
    return mapping

# Verify all inputs before writing any generated file. New source pins require
# an explicit reviewed change to the manifest, never implicit regeneration.
expected_hashes = {entry['protocol']: entry['sha256'] for entry in
                   json.loads((ROOT / 'research/schema-hashes.json').read_text())}
for protocol, (version, _) in FAMILIES.items():
    data = (ROOT / 'research/protocols' / f'{version}.json').read_bytes()
    if hashlib.sha256(data).hexdigest() != expected_hashes[protocol]:
        raise SystemExit(f'Schema hash mismatch for protocol {protocol}')

HEADER = '// Generated by tools/generate_catalog.py. See PROVENANCE.md.\n'
IMPORTS = 'use super::{PacketInfo, State, Direction};\n'
destination = ROOT / 'src/catalog'
destination.mkdir(exist_ok=True)
modules = [HEADER, IMPORTS]
paths = []
provenance = []
for protocol, (version, releases) in FAMILIES.items():
    raw = (ROOT / 'research/protocols' / f'{version}.json').read_bytes()
    schema = json.loads(raw)
    out = [HEADER, IMPORTS, f'pub(crate) static P{protocol}: &[PacketInfo] = &[\n']
    count = 0
    ranges = []
    for state, rust_state in STATES:
        for direction, rust_direction in DIRECTIONS:
            start = count
            packet = schema.get(state, {}).get(direction, {}).get('types', {}).get('packet')
            if packet:
                mapping = corrected_mapping(protocol, state, direction, packet[1][0]['type'][1]['mappings'])
                for wire_id, name in sorted(mapping.items()):
                    out.append(f'PacketInfo {{ state: State::{rust_state}, direction: Direction::{rust_direction}, id: {wire_id}, name: "{name}" }},\n')
                    count += 1
            ranges.append((start, count))
    out.append('];\n')
    out.append(f'pub(crate) static P{protocol}_RANGES: [(usize,usize);10] = {ranges!r};\n')
    path = destination / f'p{protocol}.rs'
    path.write_text(''.join(out))
    paths.append(path)
    modules.append(f'mod p{protocol};\npub(super) use p{protocol}::{{P{protocol},P{protocol}_RANGES}};\n')
    provenance.append({'protocol': protocol, 'releases': releases, 'schema': version,
                       'sha256': hashlib.sha256(raw).hexdigest()})
index = destination / 'mod.rs'
index.write_text(''.join(modules))
paths.append(index)
(ROOT / 'research/schema-hashes.json').write_text(json.dumps(provenance, indent=2) + '\n')
if not shutil.which('rustfmt'):
    raise SystemExit('Install rustfmt to format generated modules')
subprocess.run(['rustfmt', '--edition', '2021', *map(str, paths)], check=True)
print(f'Generated {len(paths)} Rust catalog modules')
